clear; clc;
M = dlmread("results/vpa_stiff_test_2016_arg_arc.csv",';', 1, 0);
l = M(:, 1);
phi = M(:, 2);
z = M(:, 3);
h_z = M(:, 4);
uInitWave = M(:, 5);
tInitWave = M(:, 6);
uWave = M(:, 7);
tWave = M(:, 8);
u = M(:, 9);
t = M(:, 10);
uExact = M(:, 11);
tExact = M(:, 12);

% сетки
% по действительной оси
plot(real(l), imag(l), 'Marker', 'o',...
    'Color', 'magenta',...
    'LineStyle', '-');
hold on;
% по замкнутому контуру в комплексной плоскости
plot(real(z), imag(z), 'Marker', 'o',...
    'Color', 'black',...
    'LineStyle', '-');
hold on;
% шаги по контуру (визуализация)
for i = 1 : 1 : length(z)
    plot([real( z(i) ); real( z(i)+h_z(i) )],...
        [imag( z(i) ); imag( z(i)+h_z(i) )], 'Marker', 'none',...
    'Color', 'red',...
    'LineStyle', '-');
end


% решение
figure();
plot(t, u, 'Marker', 'o',...
    'MarkerSize', 5,...
    'MarkerFaceColor', 'black',...
    'MarkerEdgeColor', 'black',...
    'Color', 'black',...
    'LineStyle', '-');
hold on;
plot(tExact, uExact, 'Marker', 'o',...
    'MarkerSize', 5,...
    'MarkerFaceColor', 'red',...
    'MarkerEdgeColor', 'red',...
    'Color', 'red',...
    'LineStyle', '-');
legend('calc', 'exact');

